"""Generate markdown API reference docs from the wrapped Aryeo OpenAPI spec.

The source of truth for the API is ``docs/api/aryeo.json``. This script unwraps
the actual OpenAPI document from the top-level ``definition`` key and renders a
small, deterministic markdown reference tree under ``docs/api/``.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

JsonDict = dict[str, Any]
HTTP_METHODS = ("get", "post", "put", "patch", "delete", "options", "head", "trace")
GENERATED_BANNER = (
    "<!-- Generated by docs/api/generate_reference.py. Do not edit directly. -->"
)


@dataclass(frozen=True)
class ParameterRecord:
    """Represents a documented operation parameter.

    Attributes:
        name: Parameter name as shown in the API.
        location: Where the parameter is supplied, such as ``query`` or ``path``.
        required: Whether the parameter is required.
        description: Human-readable parameter description.
        schema_summary: Short rendered schema summary for the parameter value.
    """

    name: str
    location: str
    required: bool
    description: str
    schema_summary: str


@dataclass(frozen=True)
class RequestBodyRecord:
    """Represents a summarized request body.

    Attributes:
        required: Whether the request body is required.
        content_types: Summary lines keyed by content type.
    """

    required: bool
    content_types: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class ResponseRecord:
    """Represents a summarized operation response.

    Attributes:
        status_code: HTTP status code.
        description: Human-readable response description.
        content_types: Summary lines keyed by content type.
    """

    status_code: str
    description: str
    content_types: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class OperationRecord:
    """Represents a normalized API operation.

    Attributes:
        tag: Primary OpenAPI tag used to group the operation.
        path: API path template.
        method: Uppercase HTTP method.
        operation_id: Operation identifier from the OpenAPI spec.
        summary: Short operation summary.
        description: Longer operation description.
        auth_label: Human-readable authentication summary.
        is_public: Whether the operation is callable without authentication.
        parameters: Normalized parameter records.
        request_body: Optional normalized request body record.
        responses: Normalized response records in spec order.
        schema_refs: Unique schema names referenced anywhere in the operation.
    """

    tag: str
    path: str
    method: str
    operation_id: str
    summary: str
    description: str
    auth_label: str
    is_public: bool
    parameters: tuple[ParameterRecord, ...]
    request_body: RequestBodyRecord | None
    responses: tuple[ResponseRecord, ...]
    schema_refs: tuple[str, ...]


@dataclass(frozen=True)
class TagRecord:
    """Represents a top-level tag and its grouped operations.

    Attributes:
        name: Tag display name from the OpenAPI spec.
        description: Tag description from the OpenAPI spec.
        slug: Stable kebab-case slug used for the markdown file name.
        operations: Operations assigned to the tag in deterministic order.
    """

    name: str
    description: str
    slug: str
    operations: tuple[OperationRecord, ...]


@dataclass(frozen=True)
class ApiSummary:
    """Represents high-level API statistics used across generated docs.

    Attributes:
        title: API title from the spec.
        version: API version from the spec.
        server_url: Primary server URL.
        tag_count: Number of tag groups.
        path_count: Number of unique paths.
        operation_count: Number of operations.
        schema_count: Number of component schemas.
        public_operation_count: Number of public operations.
    """

    title: str
    version: str
    server_url: str
    tag_count: int
    path_count: int
    operation_count: int
    schema_count: int
    public_operation_count: int


class ApiDocGenerator:
    """Generate markdown reference documentation from an OpenAPI wrapper."""

    def __init__(self, spec_path: Path, output_dir: Path) -> None:
        """Initialize the generator.

        Args:
            spec_path: Path to the wrapped OpenAPI JSON file.
            output_dir: Directory where markdown files should be generated.
        """
        self.spec_path = spec_path
        self.output_dir = output_dir
        self.guides_dir = output_dir / "guides"
        self.reference_dir = output_dir / "reference"
        self.wrapper = self._load_json(spec_path)
        self.spec = self._unwrap_definition(self.wrapper)
        self.components = self.spec.get("components", {})
        self.schemas = self.components.get("schemas", {})
        self.global_security = self.spec.get("security")
        self.tags = self._build_tags()
        self.summary = self._build_summary()

    def _display_path(self, path: Path) -> str:
        """Render a stable, mostly relative path for generated markdown.

        Args:
            path: Path to display in generated output.

        Returns:
            Repository-relative path when feasible, otherwise the raw POSIX path.
        """
        try:
            repo_root = self.output_dir.parent.parent
            return path.resolve().relative_to(repo_root.resolve()).as_posix()
        except ValueError:
            return path.as_posix()

    def generate(self) -> list[Path]:
        """Render all markdown files to disk.

        Returns:
            The list of generated file paths.
        """
        self.guides_dir.mkdir(parents=True, exist_ok=True)
        self.reference_dir.mkdir(parents=True, exist_ok=True)

        files: dict[Path, str] = {
            self.output_dir / "README.md": self._render_root_readme(),
            self.guides_dir / "authentication.md": self._render_authentication_guide(),
            self.guides_dir / "errors.md": self._render_errors_guide(),
            self.guides_dir / "pagination.md": self._render_pagination_guide(),
            self.reference_dir / "README.md": self._render_reference_index(),
        }
        for tag in self.tags:
            files[self.reference_dir / f"{tag.slug}.md"] = self._render_tag_reference(
                tag
            )

        for path, content in files.items():
            path.write_text(content, encoding="utf-8")
        return sorted(files)

    @staticmethod
    def _load_json(path: Path) -> JsonDict:
        """Load a JSON file from disk.

        Args:
            path: File path to load.

        Returns:
            Parsed JSON object.
        """
        return json.loads(path.read_text(encoding="utf-8"))

    @staticmethod
    def _unwrap_definition(wrapper: JsonDict) -> JsonDict:
        """Extract the OpenAPI definition from the wrapper object.

        Args:
            wrapper: Wrapped JSON object containing the ``definition`` key.

        Returns:
            The actual OpenAPI specification.

        Raises:
            ValueError: If the wrapper does not contain an OpenAPI definition.
        """
        definition = wrapper.get("definition")
        if not isinstance(definition, dict) or "openapi" not in definition:
            raise ValueError("Expected a wrapped OpenAPI document under 'definition'.")
        return definition

    def _build_summary(self) -> ApiSummary:
        """Build reusable API summary statistics.

        Returns:
            Populated summary record for shared docs.
        """
        public_count = sum(
            1 for tag in self.tags for op in tag.operations if op.is_public
        )
        info = self.spec.get("info", {})
        servers = self.spec.get("servers", [])
        server_url = servers[0].get("url", "Unknown") if servers else "Unknown"
        return ApiSummary(
            title=str(info.get("title", "API")),
            version=str(info.get("version", "Unknown")),
            server_url=server_url,
            tag_count=len(self.tags),
            path_count=len(self.spec.get("paths", {})),
            operation_count=sum(len(tag.operations) for tag in self.tags),
            schema_count=len(self.schemas),
            public_operation_count=public_count,
        )

    def _build_tags(self) -> tuple[TagRecord, ...]:
        """Normalize tag metadata and grouped operations.

        Returns:
            Tag records in the same order as the OpenAPI tag list.
        """
        operations_by_tag: dict[str, list[OperationRecord]] = defaultdict(list)
        for path, methods in self.spec.get("paths", {}).items():
            for method in HTTP_METHODS:
                operation = methods.get(method)
                if not isinstance(operation, dict):
                    continue
                tag_names = operation.get("tags") or ["Untagged"]
                primary_tag = str(tag_names[0])
                operations_by_tag[primary_tag].append(
                    self._build_operation(primary_tag, path, method.upper(), operation)
                )

        tag_records: list[TagRecord] = []
        for tag in self.spec.get("tags", []):
            tag_name = str(tag.get("name", "Untagged"))
            sorted_operations = tuple(
                sorted(
                    operations_by_tag.get(tag_name, []),
                    key=lambda item: (item.path, item.method, item.operation_id),
                )
            )
            tag_records.append(
                TagRecord(
                    name=tag_name,
                    description=self._clean_text(tag.get("description")),
                    slug=self._slugify(tag_name),
                    operations=sorted_operations,
                )
            )
        return tuple(tag_records)

    def _build_operation(
        self,
        tag_name: str,
        path: str,
        method: str,
        operation: JsonDict,
    ) -> OperationRecord:
        """Normalize an individual OpenAPI operation.

        Args:
            tag_name: Primary tag name for the operation.
            path: Path template for the operation.
            method: Uppercase HTTP method.
            operation: Raw OpenAPI operation object.

        Returns:
            Normalized operation record.
        """
        parameters = tuple(
            self._build_parameter(parameter)
            for parameter in operation.get("parameters", [])
            if isinstance(parameter, dict)
        )
        request_body = self._build_request_body(operation.get("requestBody"))
        responses = tuple(
            self._build_response(status_code, response)
            for status_code, response in operation.get("responses", {}).items()
            if isinstance(response, dict)
        )
        schema_refs = tuple(sorted(self._collect_schema_refs(operation)))
        is_public = self._is_public_operation(operation.get("security"))
        auth_label = "Public" if is_public else "Bearer token required"
        return OperationRecord(
            tag=tag_name,
            path=path,
            method=method,
            operation_id=str(operation.get("operationId", "")),
            summary=self._clean_text(operation.get("summary")),
            description=self._clean_text(operation.get("description")),
            auth_label=auth_label,
            is_public=is_public,
            parameters=parameters,
            request_body=request_body,
            responses=responses,
            schema_refs=schema_refs,
        )

    def _build_parameter(self, parameter: JsonDict) -> ParameterRecord:
        """Normalize an OpenAPI parameter object.

        Args:
            parameter: Raw parameter object.

        Returns:
            Normalized parameter record.
        """
        schema = parameter.get("schema", {})
        return ParameterRecord(
            name=str(parameter.get("name", "")),
            location=str(parameter.get("in", "")),
            required=bool(parameter.get("required", False)),
            description=self._clean_text(parameter.get("description")),
            schema_summary=self._summarize_schema(schema),
        )

    def _build_request_body(self, request_body: Any) -> RequestBodyRecord | None:
        """Normalize an OpenAPI request body object.

        Args:
            request_body: Raw request body object or ``None``.

        Returns:
            Normalized request body record, if present.
        """
        if not isinstance(request_body, dict):
            return None
        content_types = tuple(
            (
                content_type,
                self._summarize_schema(content.get("schema", {})),
            )
            for content_type, content in request_body.get("content", {}).items()
            if isinstance(content, dict)
        )
        return RequestBodyRecord(
            required=bool(request_body.get("required", False)),
            content_types=content_types,
        )

    def _build_response(self, status_code: str, response: JsonDict) -> ResponseRecord:
        """Normalize an OpenAPI response object.

        Args:
            status_code: HTTP status code.
            response: Raw response object.

        Returns:
            Normalized response record.
        """
        content_types = tuple(
            (
                content_type,
                self._summarize_schema(content.get("schema", {})),
            )
            for content_type, content in response.get("content", {}).items()
            if isinstance(content, dict)
        )
        return ResponseRecord(
            status_code=status_code,
            description=self._clean_text(response.get("description")),
            content_types=content_types,
        )

    def _is_public_operation(self, security: Any) -> bool:
        """Determine whether an operation is public.

        Args:
            security: Operation-level security definition.

        Returns:
            ``True`` when the operation is callable without authentication.
        """
        if security == []:
            return True
        if security is None:
            return self.global_security == []
        return False

    @staticmethod
    def _slugify(value: str) -> str:
        """Convert a string to a stable kebab-case slug.

        Args:
            value: Human-readable string.

        Returns:
            Kebab-case slug.
        """
        slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
        return slug or "untagged"

    @staticmethod
    def _clean_text(value: Any) -> str:
        """Normalize a doc string into a compact markdown-safe sentence.

        Args:
            value: Raw text value.

        Returns:
            Cleaned string with collapsed whitespace.
        """
        text = str(value or "").strip()
        return re.sub(r"\s+", " ", text)

    @staticmethod
    def _escape_table_cell(value: str) -> str:
        """Escape markdown table content.

        Args:
            value: Raw cell value.

        Returns:
            Escaped cell value.
        """
        return value.replace("|", "\\|").replace("\n", "<br>")

    def _summarize_schema(self, schema: Any) -> str:
        """Render a compact schema summary for markdown.

        Args:
            schema: Raw schema object.

        Returns:
            Compact schema summary string.
        """
        if not isinstance(schema, dict) or not schema:
            return "None"
        if "$ref" in schema:
            return f"`{self._ref_name(str(schema['$ref']))}`"
        for key, separator in (
            ("oneOf", " or "),
            ("anyOf", " or "),
            ("allOf", " and "),
        ):
            if key in schema:
                return self._join_schema_summaries(schema[key], separator)
        if schema.get("type") == "array":
            item_summary = self._summarize_schema(schema.get("items", {}))
            return f"array of {item_summary}"
        if "enum" in schema:
            return self._format_enum_summary(schema.get("enum", []))
        schema_type = schema.get("type")
        if schema_type == "object":
            return self._format_object_summary(schema.get("properties", {}))
        if isinstance(schema_type, str):
            return self._format_primitive_summary(
                schema_type,
                schema.get("format"),
            )
        title = schema.get("title")
        if title:
            return f"`{title}`"
        return "Schema"

    def _join_schema_summaries(self, schemas: Any, separator: str) -> str:
        """Join summarized child schemas with a compositional separator.

        Args:
            schemas: Child schema list.
            separator: Text used to join the child summaries.

        Returns:
            Joined child schema summaries.
        """

        if not isinstance(schemas, list):
            return "Schema"
        return separator.join(self._summarize_schema(item) for item in schemas)

    @staticmethod
    def _format_enum_summary(values: Any) -> str:
        """Render a compact enum preview.

        Args:
            values: Raw enum values from the schema.

        Returns:
            Human-readable enum summary string.
        """

        if not isinstance(values, list):
            return "enum"

        preview = ", ".join(f"`{item}`" for item in values[:5])
        suffix = " ..." if len(values) > 5 else ""
        return f"enum ({preview}{suffix})"

    @staticmethod
    def _format_object_summary(properties: Any) -> str:
        """Render a compact object-property preview.

        Args:
            properties: Raw properties mapping from the schema.

        Returns:
            Human-readable object summary string.
        """

        if not isinstance(properties, dict) or not properties:
            return "object"

        property_names = list(properties.keys())
        preview = ", ".join(f"`{name}`" for name in property_names[:4])
        suffix = ", ..." if len(property_names) > 4 else ""
        return f"object with {preview}{suffix}"

    @staticmethod
    def _format_primitive_summary(schema_type: str, schema_format: Any) -> str:
        """Render a primitive type summary with optional format metadata.

        Args:
            schema_type: Primitive schema type string.
            schema_format: Optional OpenAPI format hint.

        Returns:
            Human-readable primitive summary string.
        """

        if schema_format:
            return f"{schema_type} ({schema_format})"
        return schema_type

    @staticmethod
    def _ref_name(ref: str) -> str:
        """Extract the terminal name from a JSON pointer reference.

        Args:
            ref: JSON pointer reference string.

        Returns:
            Final reference segment.
        """
        return ref.rsplit("/", 1)[-1]

    def _collect_schema_refs(self, node: Any) -> set[str]:
        """Recursively collect component schema references.

        Args:
            node: Arbitrary JSON node.

        Returns:
            Set of referenced component schema names.
        """
        refs: set[str] = set()
        if isinstance(node, dict):
            ref = node.get("$ref")
            if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
                refs.add(self._ref_name(ref))
            for value in node.values():
                refs.update(self._collect_schema_refs(value))
        elif isinstance(node, list):
            for item in node:
                refs.update(self._collect_schema_refs(item))
        return refs

    def _collect_public_operations(self) -> list[OperationRecord]:
        """List public operations in deterministic order.

        Returns:
            Sorted public operations.
        """
        operations = [op for tag in self.tags for op in tag.operations if op.is_public]
        return sorted(
            operations, key=lambda item: (item.path, item.method, item.operation_id)
        )

    def _collect_error_schemas(self) -> list[tuple[str, JsonDict]]:
        """Collect shared error schemas referenced by API responses.

        Returns:
            Ordered list of schema name and schema object tuples.
        """
        names: set[str] = set()
        for tag in self.tags:
            for operation in tag.operations:
                for schema_name in operation.schema_refs:
                    if schema_name.startswith("ApiError") or schema_name.startswith(
                        "ApiFail"
                    ):
                        names.add(schema_name)
        return [
            (name, self.schemas[name]) for name in sorted(names) if name in self.schemas
        ]

    def _collect_pagination_endpoints(self) -> list[OperationRecord]:
        """Collect endpoints that expose standard pagination parameters.

        Returns:
            Sorted operations that support ``page`` and ``per_page``.
        """
        matches: list[OperationRecord] = []
        for tag in self.tags:
            for operation in tag.operations:
                parameter_names = {parameter.name for parameter in operation.parameters}
                if {"page", "per_page"}.issubset(parameter_names):
                    matches.append(operation)
        return sorted(
            matches, key=lambda item: (item.path, item.method, item.operation_id)
        )

    def _format_response_content(self, response: ResponseRecord) -> str:
        """Render response content types as a table-safe string.

        Args:
            response: Normalized response record.

        Returns:
            Table-safe content summary.
        """
        if not response.content_types:
            return "None"
        return "<br>".join(
            f"`{content_type}`: {schema_summary}"
            for content_type, schema_summary in response.content_types
        )

    def _render_root_readme(self) -> str:
        """Render the top-level API docs README.

        Returns:
            Markdown content for ``docs/api/README.md``.
        """
        guide_links = "\n".join(
            [
                "- [Authentication](guides/authentication.md)",
                "- [Errors](guides/errors.md)",
                "- [Pagination](guides/pagination.md)",
                "- [Reference Index](reference/README.md)",
            ]
        )
        reference_links = "\n".join(
            [
                (
                    f"- [{tag.name}](reference/{tag.slug}.md) "
                    f"({len(tag.operations)} operations)"
                )
                for tag in self.tags
            ]
        )
        return (
            f"{GENERATED_BANNER}\n\n"
            f"# {self.summary.title} API Docs\n\n"
            "This directory contains generated markdown reference docs sourced from "
            f"`{self.spec_path.name}`.\n\n"
            "## Source Of Truth\n\n"
            f"- Spec wrapper: `{self._display_path(self.spec_path)}`\n"
            "- Actual OpenAPI document: top-level `definition` object inside "
            "the wrapper\n"
            "- Generated markdown: `README.md`, `guides/`, and `reference/`\n"
            "- Generator entrypoint: `docs/api/generate_reference.py`\n\n"
            "## Regenerate\n\n"
            "```bash\n"
            "python3 docs/api/generate_reference.py\n"
            "```\n\n"
            "## API Snapshot\n\n"
            f"- Version: `{self.summary.version}`\n"
            f"- Primary server: `{self.summary.server_url}`\n"
            f"- Tags: `{self.summary.tag_count}`\n"
            f"- Paths: `{self.summary.path_count}`\n"
            f"- Operations: `{self.summary.operation_count}`\n"
            f"- Component schemas: `{self.summary.schema_count}`\n"
            f"- Public operations: `{self.summary.public_operation_count}`\n\n"
            "## Shared Guides\n\n"
            f"{guide_links}\n\n"
            "## Tag Reference\n\n"
            f"{reference_links}\n"
        )

    def _render_authentication_guide(self) -> str:
        """Render the authentication guide page.

        Returns:
            Markdown content for ``guides/authentication.md``.
        """
        public_operations = self._collect_public_operations()
        public_lines = "\n".join(
            [
                f"- `{operation.method} {operation.path}` in `{operation.tag}`"
                for operation in public_operations
            ]
        )
        security_schemes = self.components.get("securitySchemes", {})
        token_scheme = security_schemes.get("Token", {})
        description = self._clean_text(token_scheme.get("description"))
        return (
            f"{GENERATED_BANNER}\n\n"
            "# Authentication\n\n"
            "Most operations in the Aryeo API require a bearer token supplied in the "
            "`Authorization` header.\n\n"
            "## Security Scheme\n\n"
            f"- Scheme name: `Token`\n"
            f"- Type: `{token_scheme.get('type', 'Unknown')}`\n"
            f"- HTTP scheme: `{token_scheme.get('scheme', 'Unknown')}`\n"
            f"- Description: {description or 'No description provided.'}\n\n"
            "## Example Header\n\n"
            "```http\n"
            "Authorization: Bearer <personal-access-token>\n"
            "```\n\n"
            "## Authentication Behavior\n\n"
            f"- Protected operations: `"
            f"{self.summary.operation_count - self.summary.public_operation_count}`\n"
            f"- Public operations: `{self.summary.public_operation_count}`\n"
            "- The OpenAPI document does not apply authentication globally; it opts "
            "individual protected endpoints into bearer-token auth.\n\n"
            "## Public Operations\n\n"
            f"{public_lines}\n"
        )

    def _render_errors_guide(self) -> str:
        """Render the shared error guide page.

        Returns:
            Markdown content for ``guides/errors.md``.
        """
        rows: list[str] = []
        for name, schema in self._collect_error_schemas():
            properties = ", ".join(
                f"`{item}`" for item in schema.get("properties", {}).keys()
            )
            rows.append(
                "| "
                + " | ".join(
                    [
                        f"`{name}`",
                        self._escape_table_cell(
                            self._clean_text(schema.get("description"))
                        ),
                        self._escape_table_cell(properties or "None"),
                    ]
                )
                + " |"
            )
        table = "\n".join(rows)
        return (
            f"{GENERATED_BANNER}\n\n"
            "# Errors\n\n"
            "The OpenAPI spec reuses a small set of shared error schemas across 4xx "
            "and 5xx responses.\n\n"
            "## Shared Error Schemas\n\n"
            "| Schema | Description | Fields |\n"
            "| --- | --- | --- |\n"
            f"{table}\n\n"
            "## Typical Error Status Codes\n\n"
            "- `403`: authorization or access failures\n"
            "- `404`: requested resource was not found\n"
            "- `409`: conflict or incompatible state\n"
            "- `422`: validation failures\n"
            "- `500`: unexpected server failures\n"
        )

    def _render_pagination_guide(self) -> str:
        """Render the pagination guide page.

        Returns:
            Markdown content for ``guides/pagination.md``.
        """
        endpoints = self._collect_pagination_endpoints()
        endpoint_lines = "\n".join(
            [
                f"- `{operation.method} {operation.path}` in `{operation.tag}`"
                for operation in endpoints
            ]
        )
        pagination_meta = self.schemas.get("PaginationMeta", {})
        pagination_links = self.schemas.get("PaginationLinks", {})
        meta_fields = ", ".join(
            f"`{field}`" for field in pagination_meta.get("properties", {}).keys()
        )
        link_fields = ", ".join(
            f"`{field}`" for field in pagination_links.get("properties", {}).keys()
        )
        return (
            f"{GENERATED_BANNER}\n\n"
            "# Pagination\n\n"
            "List-style endpoints commonly use the `page` and `per_page` query "
            "parameters to page through results.\n\n"
            "## Common Query Parameters\n\n"
            "- `page`: selects the current page of results\n"
            "- `per_page`: limits results returned per page\n"
            "- `sort`: applies supported sort ordering\n"
            "- `include`: expands related resources when supported\n\n"
            "## Shared Pagination Schemas\n\n"
            f"- `PaginationMeta`: {meta_fields or 'No fields found'}\n"
            f"- `PaginationLinks`: {link_fields or 'No fields found'}\n\n"
            "## Endpoints With Standard Pagination Parameters\n\n"
            f"{endpoint_lines}\n"
        )

    def _render_reference_index(self) -> str:
        """Render the reference index page.

        Returns:
            Markdown content for ``reference/README.md``.
        """
        rows = "\n".join(
            [
                "| "
                + " | ".join(
                    [
                        f"[{tag.name}]({tag.slug}.md)",
                        str(len(tag.operations)),
                        self._escape_table_cell(
                            tag.description or "No description provided."
                        ),
                    ]
                )
                + " |"
                for tag in self.tags
            ]
        )
        return (
            f"{GENERATED_BANNER}\n\n"
            "# Reference Index\n\n"
            "The files in this directory group operations by their primary "
            "OpenAPI tag.\n\n"
            "| Tag | Operations | Description |\n"
            "| --- | ---: | --- |\n"
            f"{rows}\n"
        )

    def _render_tag_reference(self, tag: TagRecord) -> str:
        """Render a single tag reference page.

        Args:
            tag: Tag record to render.

        Returns:
            Markdown content for the tag markdown file.
        """
        operations_table = "\n".join(
            [
                "| "
                + " | ".join(
                    [
                        f"`{operation.method}`",
                        f"`{operation.path}`",
                        self._escape_table_cell(
                            operation.summary or "No summary provided."
                        ),
                        operation.auth_label,
                    ]
                )
                + " |"
                for operation in tag.operations
            ]
        )
        operation_sections = "\n\n".join(
            self._render_operation_section(operation) for operation in tag.operations
        )
        return (
            f"{GENERATED_BANNER}\n\n"
            f"# {tag.name}\n\n"
            f"{tag.description or 'No description provided.'}\n\n"
            "## Operations At A Glance\n\n"
            "| Method | Path | Summary | Auth |\n"
            "| --- | --- | --- | --- |\n"
            f"{operations_table}\n\n"
            f"{operation_sections}\n"
        )

    def _render_operation_section(self, operation: OperationRecord) -> str:
        """Render a full section for one operation.

        Args:
            operation: Operation record to render.

        Returns:
            Markdown content for one operation section.
        """
        parameter_block = self._render_parameter_block(operation.parameters)
        request_body_block = self._render_request_body_block(operation.request_body)
        response_block = self._render_response_block(operation.responses)
        schema_refs = (
            ", ".join(f"`{name}`" for name in operation.schema_refs)
            if operation.schema_refs
            else "None"
        )
        return (
            f"## `{operation.method} {operation.path}`\n\n"
            f"{operation.summary or 'No summary provided.'}\n\n"
            f"{operation.description or 'No description provided.'}\n\n"
            f"- Operation ID: `{operation.operation_id}`\n"
            f"- Authentication: {operation.auth_label}\n"
            f"- Related schemas: {schema_refs}\n\n"
            f"{parameter_block}\n\n"
            f"{request_body_block}\n\n"
            f"{response_block}"
        )

    def _render_parameter_block(self, parameters: Iterable[ParameterRecord]) -> str:
        """Render the parameter subsection for an operation.

        Args:
            parameters: Parameter records to render.

        Returns:
            Markdown subsection content.
        """
        parameter_list = list(parameters)
        if not parameter_list:
            return "### Parameters\n\nNone."
        rows = "\n".join(
            [
                "| "
                + " | ".join(
                    [
                        f"`{parameter.name}`",
                        f"`{parameter.location}`",
                        "Yes" if parameter.required else "No",
                        self._escape_table_cell(parameter.schema_summary),
                        self._escape_table_cell(
                            parameter.description or "No description provided."
                        ),
                    ]
                )
                + " |"
                for parameter in parameter_list
            ]
        )
        return (
            "### Parameters\n\n"
            "| Name | In | Required | Schema | Description |\n"
            "| --- | --- | --- | --- | --- |\n"
            f"{rows}"
        )

    def _render_request_body_block(self, request_body: RequestBodyRecord | None) -> str:
        """Render the request-body subsection for an operation.

        Args:
            request_body: Request body record, if present.

        Returns:
            Markdown subsection content.
        """
        if request_body is None:
            return "### Request Body\n\nNone."
        rows = "\n".join(
            [
                f"- `{content_type}`: {schema_summary}"
                for content_type, schema_summary in request_body.content_types
            ]
        )
        required_label = "Yes" if request_body.required else "No"
        return "### Request Body\n\n" f"- Required: {required_label}\n" f"{rows}"

    def _render_response_block(self, responses: Iterable[ResponseRecord]) -> str:
        """Render the responses subsection for an operation.

        Args:
            responses: Response records to render.

        Returns:
            Markdown subsection content.
        """
        response_list = list(responses)
        if not response_list:
            return "### Responses\n\nNone."
        rows = "\n".join(
            [
                "| "
                + " | ".join(
                    [
                        f"`{response.status_code}`",
                        self._escape_table_cell(
                            response.description or "No description provided."
                        ),
                        self._escape_table_cell(
                            self._format_response_content(response)
                        ),
                    ]
                )
                + " |"
                for response in response_list
            ]
        )
        return (
            "### Responses\n\n"
            "| Status | Description | Content |\n"
            "| --- | --- | --- |\n"
            f"{rows}"
        )


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for the generator.

    Returns:
        Parsed command-line namespace.
    """
    parser = argparse.ArgumentParser(
        description="Generate markdown API docs from docs/api/aryeo.json."
    )
    parser.add_argument(
        "--spec-path",
        type=Path,
        default=Path(__file__).with_name("aryeo.json"),
        help="Path to the wrapped OpenAPI JSON file.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Directory where markdown files should be written.",
    )
    return parser.parse_args()


def main() -> None:
    """Run the markdown generator CLI."""
    args = parse_args()
    generator = ApiDocGenerator(spec_path=args.spec_path, output_dir=args.output_dir)
    generated_files = generator.generate()
    print(f"Generated {len(generated_files)} files:")
    for path in generated_files:
        print(f"- {path.relative_to(args.output_dir.parent)}")


if __name__ == "__main__":
    main()
